### ISSUE TITLE
Only show buttons for available sensors

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/Air-Quality-Web#16] opened 2019-02-25 15:50 UTC
**Could the graph display (and other such like) only show buttons for available sensors.**

e.g. if it's a PM2.5/10 only setup, then don't show temp/humidity/pressure/..
If it's a temp monitor only, only show temp, not PM buttons etc.
 

Not anything urgent, but as more sensors are added, some maybe PM only, some may be VOC and no PM
Also if IAQ, VOC, O3, CO2 start being monitored, they may not have the other sensors.

As test subjects, currently
Matt_01 only has PM2.5, PM10 and nothing else.
robin_05 only has temp/press/humid

Maybe tied in with #11 ?

**Comment by sbrl** [comment] 2019-02-25 21:51
Yep, this is a duplicate of #11 and #12.

We already have the ability to filter the measurement types displayed - it's just that there's a lot of rogue data in the system from a bug in the broker that needs removing. I believe that @BNNorman is working on that with @robinharris.

**Closed by sbrl** 2019-02-25 21:51 UTC
